ethics_prefix: "Conc_20Ntb14_"
datadir: "/nesi/nobackup/uoa03264/ecla535/dti_pipeline_data/dicom"
resultsdir: "/nesi/nobackup/uoa03264/ecla535/dti_pipeline_data/processed"

acqparams: "config/Conc/acqparams.txt"
index: "config/Conc/index.txt"
fs_license: "config/Conc/fs_license.txt"

qc_status:
    skip_mriqc: False  # if True, skip MRIQC reports generation, only make QC status files
    default: False  # default value for entries in QC status files

resources:
  partition: milan
  cpus: 1
  gpu: 0
  mem_mb: 4000
  runtime: 120
        
# HeuDiConv options
# modify 'grouping' to modify how to group dicoms (default: by studyUID)
# if using "custom", make sure to modify the heuristic file accordingly too
# see https://heudiconv.readthedocs.io/en/latest/heuristics.html#grouping-string-or-grouping-files-dcmfilter-seqinfo
heudiconv:
    heuristic: config/Conc/heuristic.py
    threads: 2
    mem_mb: 4000
    time_min: 60
    # grouping: "custom"

# MRIQC options
# modify cli_args to pass additional arguments to the tool
# for example, use
#   cli_args: "-vvv"
# to increase the verbosity to debugging level
# see https://mriqc.readthedocs.io/en/stable/running.html#command-line-interface for available arguments
mriqc:
    mem_mb: 16000
    time_min: 120
    threads: 8
    cli_args: ""

synb0_disco:
    threads: 2
    mem_mb: 50000
    time_min: 300

hd_bet:
    extra_args: "-tta 0 -mode fast -device cpu"
    threads: 1
    mem_mb: 4000
    time_min: 20

denoise:
    threads: 2
    mem_mb: 2000
    time_min: 10

ringing_correction:
    threads: 2
    mem_mb: 2000
    time_min: 10

eddy:
    executable: "eddy_cuda10.2"  # support eddy_cuda10.2 or eddy_cpu
    extra_args: "--fwhm=0 --flm=quadratic --cnr_maps --repol --mporder=6 --residuals"
    threads: 2
    mem_mb: 4000
    time_min: 60
    gpu: "P100:1"
    slurm_extra: "--partition gpu"

eddy_quad:
    threads: 2
    mem_mb: 2000
    time_min: 30

eddy_squad:
    threads: 2
    mem_mb: 2000
    time_min: 30

freesurfer:
    license_path: ./config/license.txt  # you need to specify yours here
    mem_mb: 4000
    time_min: 660
    threads: 8